### job 配置项
jobs:
  agent:
    image: registry.erda.cloud/erda-actions/action-agent:2.2-alpha-20220606145943-831627f7a
    labels:
      # 必填字段
      MD5: e598a65e519e389b7af912d9210f267a
    envs:
      # DEBUG mode, will produce more logs
      DEBUG: false
      # push log to collector
      ENABLE_PUSH_LOG_TO_COLLECTOR: false
      STDERR_REGEXP_LIST: '["^[a-z]*can*","^[a-z]*fail*"]'
      ENCRYPTED_VAlUE_MIN_LEN: 6
      FILE_STREAM_TIMEOUT_SEC: 60
