### job 配置项
jobs:
  agent:
    image: registry.erda.cloud/erda-actions/action-agent:2.1-alpha-20220424192546-1c9a857f1
    labels:
      # 必填字段
      MD5: d8c42a46adbb1c328dcf746565eb8052
    envs:
      # DEBUG mode, will produce more logs
      DEBUG: false
      # push log to collector
      ENABLE_PUSH_LOG_TO_COLLECTOR: false
      STDERR_REGEXP_LIST: '["^[a-z]*can*","^[a-z]*fail*"]'
      ENCRYPTED_VAlUE_MIN_LEN: 6
